/*
 * The Clear BSD License
 * Copyright 2017-2018 NXP
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted (subject to the limitations in the disclaimer below) provided
 * that the following conditions are met:
 *
 * o Redistributions of source code must retain the above copyright notice, this list
 *   of conditions and the following disclaimer.
 *
 * o Redistributions in binary form must reproduce the above copyright notice, this
 *   list of conditions and the following disclaimer in the documentation and/or
 *   other materials provided with the distribution.
 *
 * o Neither the name of the copyright holder nor the names of its
 *   contributors may be used to endorse or promote products derived from this
 *   software without specific prior written permission.
 *
 * NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY THIS LICENSE.
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v4.1
processor: MIMXRT1052xxxxB
package_id: MIMXRT1052DVL6B
mcu_data: ksdk2_0
processor_version: 0.0.0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 * 
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 * 
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void) {
    BOARD_InitPins();
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: L14, peripheral: LPUART1, signal: RX, pin_signal: GPIO_AD_B0_13, software_input_on: Disable, hysteresis_enable: Disable, pull_up_down_config: Pull_Down_100K_Ohm,
    pull_keeper_select: Keeper, pull_keeper_enable: Enable, open_drain: Disable, speed: MHZ_100, drive_strength: R0_6, slew_rate: Slow}
  - {pin_num: K14, peripheral: LPUART1, signal: TX, pin_signal: GPIO_AD_B0_12, software_input_on: Disable, hysteresis_enable: Disable, pull_up_down_config: Pull_Down_100K_Ohm,
    pull_keeper_select: Keeper, pull_keeper_enable: Enable, open_drain: Disable, speed: MHZ_100, drive_strength: R0_6, slew_rate: Slow}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {
  CLOCK_EnableClock(kCLOCK_Iomuxc);           /* iomuxc clock (iomuxc_clk_enable): 0x03u */

//  IOMUXC_SetPinMux(
//      IOMUXC_GPIO_AD_B0_12_LPUART1_TX,        /* GPIO_AD_B0_12 is configured as LPUART1_TX */
//      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
//  IOMUXC_SetPinMux(
//      IOMUXC_GPIO_AD_B0_13_LPUART1_RX,        /* GPIO_AD_B0_13 is configured as LPUART1_RX */
//      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
//  IOMUXC_SetPinConfig(
//      IOMUXC_GPIO_AD_B0_12_LPUART1_TX,        /* GPIO_AD_B0_12 PAD functional properties : */
//      0x10B0u);                               /* Slew Rate Field: Slow Slew Rate
//                                                 Drive Strength Field: R0/6
//                                                 Speed Field: medium(100MHz)
//                                                 Open Drain Enable Field: Open Drain Disabled
//                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
//                                                 Pull / Keep Select Field: Keeper
//                                                 Pull Up / Down Config. Field: 100K Ohm Pull Down
//                                                 Hyst. Enable Field: Hysteresis Disabled */
//  IOMUXC_SetPinConfig(
//      IOMUXC_GPIO_AD_B0_13_LPUART1_RX,        /* GPIO_AD_B0_13 PAD functional properties : */
//      0x10B0u);                               /* Slew Rate Field: Slow Slew Rate
//                                                 Drive Strength Field: R0/6
//                                                 Speed Field: medium(100MHz)
//                                                 Open Drain Enable Field: Open Drain Disabled
//                                                 Pull / Keep Enable Field: Pull/Keeper Enabled
//                                                 Pull / Keep Select Field: Keeper
//                                                 Pull Up / Down Config. Field: 100K Ohm Pull Down
//                                                 Hyst. Enable Field: Hysteresis Disabled */

       
       /* 
        * DS18B20 
        */
        IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_12_GPIO1_IO12,  0U);                
        IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_12_GPIO1_IO12,0x10B0u);
        
        
     /*
      * Battary Vol ADC sample Pin 0xB0u 
      */
        IOMUXC_SetPinMux(IOMUXC_GPIO_AD_B0_13_GPIO1_IO13,  0U);                
        IOMUXC_SetPinConfig(IOMUXC_GPIO_AD_B0_13_GPIO1_IO13,0xB0u);

        
      /*
       *  use lpuart5 
       */       
        IOMUXC_SetPinMux(
          IOMUXC_GPIO_B1_12_LPUART5_TX,        
          0U);                             
        IOMUXC_SetPinMux(
          IOMUXC_GPIO_B1_13_LPUART5_RX, 
          0U);                             
        IOMUXC_SetPinConfig(
          IOMUXC_GPIO_B1_12_LPUART5_TX, 
          0x10B0u);                        
        IOMUXC_SetPinConfig(
          IOMUXC_GPIO_B1_13_LPUART5_RX, 
          0x10B0u);
      
      /*
       * LED indicator
       */
      
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_B1_03_GPIO1_IO19,           
      0U);                
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_B1_03_GPIO1_IO19,     
      0x10B0u);
      
      /*
       * Relay contorl pin
       */ 
  IOMUXC_SetPinMux(
      IOMUXC_GPIO_AD_B0_04_GPIO1_IO04,           
      0U);                
  IOMUXC_SetPinConfig(
      IOMUXC_GPIO_AD_B0_04_GPIO1_IO04,     
      0x10B0u);
      
      
      /*
       * OLED pin initial Group1 and Group2 
       */ 
    IOMUXC_SetPinMux( IOMUXC_SNVS_PMIC_STBY_REQ_GPIO5_IO02, 0U);          // SCL      
    IOMUXC_SetPinConfig( IOMUXC_SNVS_PMIC_STBY_REQ_GPIO5_IO02,0x10B0u);
    IOMUXC_SetPinMux( IOMUXC_GPIO_SD_B1_04_GPIO3_IO04, 0U);             // SDA      
    IOMUXC_SetPinConfig( IOMUXC_GPIO_SD_B1_04_GPIO3_IO04,0x10B0u);
    IOMUXC_SetPinMux( IOMUXC_GPIO_SD_B1_02_GPIO3_IO02, 0U);             // RST      
    IOMUXC_SetPinConfig( IOMUXC_GPIO_SD_B1_02_GPIO3_IO02,0x10B0u);
    IOMUXC_SetPinMux( IOMUXC_GPIO_B1_14_GPIO2_IO30, 0U);                // D/C      
    IOMUXC_SetPinConfig( IOMUXC_GPIO_B1_14_GPIO2_IO30,0x10B0u);
    IOMUXC_SetPinMux( IOMUXC_GPIO_AD_B1_04_GPIO1_IO20, 0U);             // CS      
    IOMUXC_SetPinConfig( IOMUXC_GPIO_AD_B1_04_GPIO1_IO20,0x18B0U);

    IOMUXC_SetPinMux( IOMUXC_SNVS_PMIC_ON_REQ_GPIO5_IO01, 0U);          // SCL      
    IOMUXC_SetPinConfig( IOMUXC_SNVS_PMIC_ON_REQ_GPIO5_IO01,0x10B0u);
    IOMUXC_SetPinMux( IOMUXC_GPIO_SD_B1_05_GPIO3_IO05, 0U);             // SDA      
    IOMUXC_SetPinConfig( IOMUXC_GPIO_SD_B1_05_GPIO3_IO05,0x10B0u);
    IOMUXC_SetPinMux( IOMUXC_GPIO_SD_B1_03_GPIO3_IO03, 0U);             // RST      
    IOMUXC_SetPinConfig( IOMUXC_GPIO_SD_B1_03_GPIO3_IO03,0x10B0u);
    IOMUXC_SetPinMux( IOMUXC_GPIO_B1_15_GPIO2_IO31, 0U);                // D/C      
    IOMUXC_SetPinConfig( IOMUXC_GPIO_B1_15_GPIO2_IO31,0x10B0u);
    IOMUXC_SetPinMux( IOMUXC_GPIO_AD_B1_05_GPIO1_IO21, 0U);             // CS      
    IOMUXC_SetPinConfig( IOMUXC_GPIO_AD_B1_05_GPIO1_IO21,0x10B0u);  
  
  /*
   *  Beep pin
   */
  IOMUXC_SetPinMux( IOMUXC_GPIO_AD_B0_00_GPIO1_IO00, 0U);             // beep      
  IOMUXC_SetPinConfig( IOMUXC_GPIO_AD_B0_00_GPIO1_IO00,0x10B0u);  
  
  
  /*
   * AS1053 pin  7pins totally
   */
   
  IOMUXC_SetPinMux( IOMUXC_GPIO_AD_B1_12_LPSPI3_PCS0, 0U);          // SPI3_CS0    XDCS
  IOMUXC_SetPinConfig( IOMUXC_GPIO_AD_B1_12_LPSPI3_PCS0,0x10B0u);
  
  IOMUXC_SetPinMux( IOMUXC_GPIO_AD_B1_13_LPSPI3_SDI, 0U);             // SPI3_MISO 
  IOMUXC_SetPinConfig( IOMUXC_GPIO_AD_B1_13_LPSPI3_SDI,0x10B0u);
  
  IOMUXC_SetPinMux( IOMUXC_GPIO_AD_B1_14_LPSPI3_SDO, 0U);             // SPI3_MOSI
  IOMUXC_SetPinConfig( IOMUXC_GPIO_AD_B1_14_LPSPI3_SDO,0x10B0u);
  
  IOMUXC_SetPinMux( IOMUXC_GPIO_AD_B1_15_LPSPI3_SCK, 0U);             // SPI3_SCK
  IOMUXC_SetPinConfig( IOMUXC_GPIO_AD_B1_15_LPSPI3_SCK,0x10B0u);
  
  IOMUXC_SetPinMux( IOMUXC_GPIO_AD_B0_14_GPIO1_IO14, 0U);             // REQ
  IOMUXC_SetPinConfig( IOMUXC_GPIO_AD_B0_14_GPIO1_IO14,0x10B0u);  
  
  IOMUXC_SetPinMux( IOMUXC_GPIO_AD_B0_15_GPIO1_IO15, 0U);             // RST
  IOMUXC_SetPinConfig( IOMUXC_GPIO_AD_B0_15_GPIO1_IO15,0x10B0u);  
  
/*  IOMUXC_SetPinMux( IOMUXC_GPIO_AD_B0_04_LPSPI3_PCS1, 0U);         */  // SPI3_CS1  this Pin is temporatory used for relay.
/*  IOMUXC_SetPinConfig( IOMUXC_GPIO_AD_B0_04_LPSPI3_PCS1,0x10B0u);  */

  IOMUXC_SetPinMux( IOMUXC_GPIO_AD_B0_05_LPSPI3_PCS2, 0U);          // SPI3_CS2    XCS
  IOMUXC_SetPinConfig( IOMUXC_GPIO_AD_B0_05_LPSPI3_PCS2,0x10B0u);  
   

  /* 
   * only one independent key in thsi board
   */
  IOMUXC_SetPinMux(
      IOMUXC_SNVS_WAKEUP_GPIO5_IO00,          /* WAKEUP is configured as GPIO5_IO00 */
      0U);                                    /* Software Input On Field: Input Path is determined by functionality */
  IOMUXC_SetPinConfig(
      IOMUXC_SNVS_WAKEUP_GPIO5_IO00,          /* WAKEUP PAD functional properties : 22K pull up */
      0x01F0A0U);     // 0x01F0A0U            
}
